apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yoloscribe-discord-bot.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yoloscribe-discord-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  discord-bot-token: {{ .Values.discordBotToken | quote }}
  discord-aes-key: {{ .Values.discordAesKey | quote }}
  supabase-service-role-key: {{ .Values.supabaseServiceRoleKey | quote }}
