{{- if .Values.ghcr.pat }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yoloscribe-indexer.fullname" . }}-ghcr
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yoloscribe-indexer.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": {{ .Values.ghcr.username | quote }},
          "password": {{ .Values.ghcr.pat | quote }},
          "auth": {{ printf "%s:%s" .Values.ghcr.username .Values.ghcr.pat | b64enc | quote }}
        }
      }
    }
{{- end }}
