"""Collects R1-R7 conformance results and renders the summary report.

A process-wide singleton (`REPORT`) is populated by each `test_rN_*.py` module
as it runs, then rendered by the `pytest_sessionfinish` hook in `conftest.py`.
"""
from __future__ import annotations

import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

_ORDER = ["R1", "R2", "R3a", "R3b", "R4", "R5", "R6", "R7"]


@dataclass
class RResult:
    id: str
    name: str
    status: str  # PASS | FAIL | PARTIAL | NOT_IMPLEMENTED
    detail: str
    checklist: dict[str, bool] | None = None

    def _lines(self) -> list[str]:
        out = [f"  {self.id:<4} {self.name:<34} {self.status:<16} {self.detail}"]
        if self.checklist:
            for key, present in sorted(self.checklist.items()):
                out.append(f"        - {key}: {'present' if present else 'absent'}")
        return out


class ConformanceReport:
    """Process-wide collector — one RResult per R-criterion, populated as tests run."""

    def __init__(self) -> None:
        self._results: dict[str, RResult] = {}

    def record(self, result: RResult) -> None:
        self._results[result.id] = result

    def has_full_session(self) -> bool:
        """True once every R1-R7 criterion has recorded a result (i.e. a `conformance-live` run)."""
        return all(key in self._results for key in _ORDER)

    def render_table(self) -> str:
        lines = ["", "=" * 78, "YoloScribe Agent Runtime — Conformance Baseline (R1-R7)", "=" * 78]
        for key in _ORDER:
            if key in self._results:
                lines.extend(self._results[key]._lines())
        missing = [key for key in _ORDER if key not in self._results]
        if missing:
            lines.append(f"  (not exercised this session: {', '.join(missing)})")
        lines.append("=" * 78)
        return "\n".join(lines)

    def render_baseline_md(self, agent_runner_ref: str) -> str:
        now = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        lines = [
            "# Conformance Baseline",
            "",
            "Generated by `make conformance-live` (`agent-runner/tests/conformance/`). "
            "Do not hand-edit — rerun the target to regenerate.",
            "",
            f"_Last verified: {now}, agent-runner @ {agent_runner_ref}_",
            "",
            "| R | Name | Status | Detail |",
            "|---|------|--------|--------|",
        ]
        for key in _ORDER:
            result = self._results.get(key)
            if result is None:
                lines.append(f"| {key} | | NOT_RUN | not exercised this session |")
                continue
            detail = result.detail.replace("|", "\\|")
            lines.append(f"| {result.id} | {result.name} | {result.status} | {detail} |")
            if result.checklist:
                for check_name, present in sorted(result.checklist.items()):
                    mark = "present" if present else "absent"
                    lines.append(f"| | &nbsp;&nbsp;{check_name} | {mark} | |")
        lines.append("")
        return "\n".join(lines)


REPORT = ConformanceReport()


def git_sha(repo_root: Path) -> str:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=repo_root, capture_output=True, text=True, timeout=5, check=True,
        )
        return out.stdout.strip()
    except Exception:
        return "unknown"
