apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "agentscribe-indexer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentscribe-indexer.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "delete", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
