{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agentscribe-backend.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentscribe-backend.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.iamRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.iamRoleArn | quote }}
  {{- end }}
{{- end }}
