image:
  repository: ghcr.io/nate-yolodev/yoloscribe-discord-bot
  tag: latest
  pullPolicy: Always

ghcr:
  username: nate-yolodev

config:
  yoloscribeApiUrl: "https://yoloscribe-dev.runyolo.dev"
  supabaseUrl: "https://logpcqkicxkeqoseajzd.supabase.co"
