{{- if .Values.otel.headers }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yoloscribe-backend.fullname" . }}-otel
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yoloscribe-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  otlp-headers: {{ .Values.otel.headers | quote }}
{{- end }}
