apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yoloscribe-messaging-bot.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yoloscribe-messaging-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  messaging-bot-secret: {{ .Values.messagingBotSecret | quote }}
  discord-bot-token: {{ .Values.discordBotToken | quote }}
